# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.CharField(max_length=30000)),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('modify_date', models.DateTimeField(verbose_name='date modified')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('modify_date', models.DateTimeField(verbose_name='date modified')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rubychina.Node')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rubychina.Node'),
        ),
    ]
